version: '3.4'
services:
  atskungfuwebapi:
    image: webapplication2
    build:
      context: .
      dockerfile: WebApplication2/Dockerfile
    ports:
      - '5000:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    command: ["dotnet", "WebApplication2.dll"]
